namespace EventContracts;

/// <summary>
/// Carries an integration-event payload together with its shared metadata.
/// </summary>
/// <typeparam name="T">The application-owned payload type.</typeparam>
public sealed record EventEnvelope<T>
    where T : notnull
{
    /// <summary>
    /// Gets the event metadata.
    /// </summary>
    public EventMetadata Metadata { get; }

    /// <summary>
    /// Gets the application-owned payload.
    /// </summary>
    public T Payload { get; }

    /// <summary>
    /// Initializes an envelope from existing metadata and a payload without changing either value.
    /// </summary>
    /// <param name="metadata">The complete metadata to preserve.</param>
    /// <param name="payload">The payload to carry.</param>
    /// <exception cref="ArgumentNullException"><paramref name="metadata"/> or <paramref name="payload"/> is <see langword="null"/>.</exception>
    public EventEnvelope(EventMetadata metadata, T payload)
    {
        ArgumentNullException.ThrowIfNull(metadata);
        ArgumentNullException.ThrowIfNull(payload);

        Metadata = metadata;
        Payload = payload;
    }

    /// <summary>
    /// Creates an envelope with a fresh event identity and caller-supplied business and workflow context.
    /// </summary>
    /// <param name="payload">The payload to carry.</param>
    /// <param name="eventType">The canonical event contract name.</param>
    /// <param name="schemaVersion">The payload schema revision.</param>
    /// <param name="occurredAt">The time the represented business fact occurred.</param>
    /// <param name="correlationId">The optional identity grouping related business work. It is never generated by this method.</param>
    /// <param name="causationId">The optional identity of the event or action that caused this event. It is never generated by this method.</param>
    /// <param name="tenantId">The optional opaque tenant context. It is never interpreted or generated by this method.</param>
    /// <param name="traceContext">The optional distributed trace context. It is independent from correlation.</param>
    /// <returns>An envelope containing a newly generated event ID and all supplied values.</returns>
#pragma warning disable CA1000 // The accepted V1 API intentionally colocates creation with EventEnvelope<T>.
    public static EventEnvelope<T> Create(
        T payload,
        EventTypeName eventType,
        SchemaVersion schemaVersion,
        DateTimeOffset occurredAt,
        CorrelationId? correlationId = null,
        CausationId? causationId = null,
        TenantId? tenantId = null,
        TraceContext? traceContext = null)
    {
        var metadata = new EventMetadata(
            EventId.New(),
            eventType,
            schemaVersion,
            occurredAt,
            correlationId,
            causationId,
            tenantId,
            traceContext);

        return new EventEnvelope<T>(metadata, payload);
    }
#pragma warning restore CA1000
}
